dssdsds

diff --git a/.github/actions/action.yaml b/.github/actions/action.yaml
--- a/.github/actions/action.yaml
+++ b/.github/actions/action.yaml
@@ -1,5 +1,6 @@
 name: Check Pull Request Commits Authors
 description: Validate pull request commits authors by email domain
+
 inputs:
   EMAIL_DOMAIN:
     description: "Email domain to be checked. For example: email-domain.com"
@@ -16,12 +17,44 @@ inputs:
 
 runs:
   using: 'composite'
+  env:
+    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
   steps:
     - name: 'Install jq'
-      shell: bash
-      run: sudo apt-get install -y jq
-    - name: 'Parse GitHub Context'
+        shell: bash
+        run: sudo apt-get install -y jq
+    - uses: actions/checkout@v3
+    - uses: octokit/request-action@v2.x
+      id: get-commits
+      with:
+        route: GET /repos/${{ inputs.GITHUB_REPOSITORY }}/pulls/${{ inputs.GITHUB_PULL_REQUEST }}/commits
+        accept-header: application/vnd.github+json
+    - name: "Checking commits authors email domain"
+      env:
+          COMMITS: ${{ steps.get-commits.outputs.data }}
       shell: bash
       run: |
-          # Parse the pull request number using jq
-          echo "${{inputs.GITHUB_PULL_REQUEST}} and ${{inputs.GITHUB_REPOSITORY}}"
+        required_email_domain=${{ inputs.EMAIL_DOMAIN }}
+        invalid_commits=0
+        for COMMIT in $(echo $COMMITS | jq -r '.[] | @base64'); do
+            _jq() {
+              echo ${COMMIT} | base64 --decode | jq -r ${1}
+            }
+            COMMIT_HASH=$(_jq '.sha')
+            COMMIT_MESSAGE=$(_jq '.commit.message')
+            COMMIT_AUTHOR=$(_jq '.commit.author.email')
+
+            echo "Cheking commit: $COMMIT_HASH"
+            echo "    Commit message: \"$COMMIT_MESSAGE\""
+            author_email_domain=${COMMIT_AUTHOR#*@}
+            if [ $author_email_domain != $required_email_domain ]; then
+                echo "    ❌ Invalid Author Email: $COMMIT_AUTHOR. Use a \`$required_email_domain\` domain email."
+                echo "    See the commit here: https://github.com/${{ inputs.GITHUB_REPOSITORY }}/pull/${{ inputs.GITHUB_PULL_REQUEST }}/commits/$COMMIT_HASH"
+                invalid_commits=$((invalid_commits+1))
+            else
+                echo "    ✅ Valid Author Email: $COMMIT_AUTHOR"
+            fi
+        done
+        if [ $invalid_commits -gt 0 ]; then
+            exit 1
+        fi
